// Code generated by "stringer -linecomment -output=token_string.go -type=Kind token.go"; DO NOT EDIT.

package css

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[EOFKind-0]
	_ = x[IdentKind-1]
	_ = x[WhitespaceKind-2]
	_ = x[FunctionKind-3]
	_ = x[AtKeywordKind-4]
	_ = x[HashKind-5]
	_ = x[StringKind-6]
	_ = x[BadStringKind-7]
	_ = x[URLKind-8]
	_ = x[BadURLKind-9]
	_ = x[DelimKind-10]
	_ = x[NumberKind-11]
	_ = x[PercentageKind-12]
	_ = x[DimensionKind-13]
	_ = x[CDOKind-14]
	_ = x[CDCKind-15]
	_ = x[ColonKind-16]
	_ = x[SemicolonKind-17]
	_ = x[CommaKind-18]
	_ = x[LBracketKind-19]
	_ = x[RBracketKind-20]
	_ = x[LParenKind-21]
	_ = x[RParenKind-22]
	_ = x[LBraceKind-23]
	_ = x[RBraceKind-24]
}

const _Kind_name = "EOFidentwhitespacefunctionat-keywordhashstringbad-stringurlbad-urldelimnumberpercentagedimensionCDOCDCcolonsemicoloncomma[](){}"

var _Kind_index = [...]uint8{0, 3, 8, 18, 26, 36, 40, 46, 56, 59, 66, 71, 77, 87, 96, 99, 102, 107, 116, 121, 122, 123, 124, 125, 126, 127}

func (i Kind) String() string {
	idx := int(i) - 0
	if i < 0 || idx >= len(_Kind_index)-1 {
		return "Kind(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _Kind_name[_Kind_index[idx]:_Kind_index[idx+1]]
}
